config/routes.rb
Rails.application.routes.draw do
  
  root "tasks#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :timers
  get "start_timer/:id", to: "timers#start_timer", as: 'start_timer'

  resources :tasks do 
    get '/page/:page', action: :index, on: :collection
  end
  
  resource :users
  get "signin", to: "users#signin"
  post "login", to: "users#login"
  
  
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_one :timer, dependent: :destroy
  accepts_nested_attributes_for :timer
  paginates_per 5

  validates :title, :assign_to,  presence: true
  validates :status ,presence:true, inclusion: { in: %w(Pending Complete) } 
  validate :administrator_only_create_task

  def administrator_only_create_task
    unless user.type == "Administrator"
      errors.add(:base, "Only Administrator have permission to create tasks.")  
    end
  end
end
  

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_params, except: [:index, :create, :new]
  before_action :check_administrator, except: [:index, :show]

  def index
    if current_user.type == "Administrator"
      @tasks = current_user.tasks.page params[:page]
    else
      @tasks = Task.where(assign_to:current_user.id).page params[:page]
    end
  end

  def show
  end

  def new
    @task = current_user.tasks.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
      TaskMailer.with(task: @task).task_assigned.deliver_now   
    else
      redirect_to new_task_path
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'   
    else
      render :edit
    end
  end

  def destroy
    if @task.destroy
      redirect_to tasks_path, notice: 'Task was successfully deleted.'
    else
      redirect_to @task,  notice: 'Something Went Wrong!!!!.'
    end
  end
  

  private
  def task_params
    params.require(:task).permit(:title, :description, :assign_to, :status, timer_attributes: [:time_in_minute, :task_id, :user_id])
  end

  def set_params
    # @task = Task.find(params[:id])
    if current_user.type == "Administrator"
      @task = current_user.tasks.find(params[:id])
      @timer = @task.timer
    else
      assign_task = Task.where(assign_to:current_user.id)
      @task = assign_task.find(params[:id])
      @timer = @task.timer
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, 'error') %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group blurred-background task-card">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-input' %>
  </div>

  <div class="form-group blurred-background task-card">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, class: 'form-input' %>
  </div>

  <div class="form-group blurred-background task-card">
    <%= form.label :assign_to, class: 'form-label' %>
    <%= form.number_field :assign_to, class: 'form-input' %>
  </div>

  <div class="form-group blurred-background task-card">
    <%= form.label :status, class: 'form-label' %>
    <%= form.text_field :status, class: 'form-input' %>
  </div>

  <%= form.fields_for :timer_attributes do |f| %>
    <div class="form-group blurred-background task-card">
      <%= f.label 'Time in Minutes', class: 'form-label' %>
      <%= f.number_field :time_in_minute, class: 'form-input' %>
    </div>

    <div class="form-group">
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>
  <% end %>
<center>
  <div class="form-group blurred-background task-card">
    <%= form.submit 'Submit', class: 'form-input' %>
  </div>
<% end %>

<div class="blurred-background task-card"><%= link_to 'Back to Tasks', tasks_path, class: 'btn btn-secondary' %> </div>
</center>

app/views/tasks/edit.html.erb
<center><h1>Editing task</h1></center>
<div class="blurred-background task-card">
<%= render "form", task: @task %>

<div>
<center>
 <div class="blurred-background task-card"> <%= link_to "Show this task", @task %> </div>
 <div class="blurred-background task-card"> <%= link_to "Back to tasks", tasks_path %> </div>
 </center>
</div>

</div>

app/views/tasks/index.html.erb
<center><h1>Tasks</h1></center>
<div id="tasks" class="blurred-background task-card">
  <% if current_user.type == "Administrator"  %>
    <div class="blurred-background task-card">
      <strong><center> <%= link_to "Create New Task", new_task_path, id: "new-task-link" %> </center> </strong>
    </div>
  <% end %>


  <% @tasks.each do |task| %>
    <div class="task-card">
      <p class="task-title">
        <strong>Task:</strong>
        <%= link_to task.title, task %>
      </p>
      <p class="task-description">
        <strong>Description:</strong>
        <%= task.description %>
      </p>
      <p class="task-assignee">
        <strong>Assign_to:</strong>
        <%= User.find(task.assign_to).name %>
      </p>
      <p class="task-status">
        <strong>Status:</strong>
        <%= task.status %>
      </p>
      <p class="task-timer">
        <strong>Timer:</strong>
        <% if task.timer.nil? %>
          <strong>NA</strong>
        <% else %>
          <%= link_to task.timer.time_in_minute, timer_path(task.timer) %>
        <% end %>
      </p>
    </div>
  <% end %>
  <center><%= paginate @tasks %></center>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<div class="blurred-background task-card">
  <%= render "form", task: @task %>
  <div class="blurred-background task-card">
  <center> <%= link_to "Back to tasks", tasks_path %> </center>
  </div>
</div>

app/views/tasks/show.html.erb
 <center>
  <u><h3> Task Details </h3></u>
 </center> 
<div class="blurred-background task-card">
  <p>
    <strong>Task:</strong>
    <%= link_to @task.title, @task %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @task.description %>
  </p>

  <p>
    <strong>Assign_to:</strong>
    <%= User.find(@task.assign_to).name  %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @task.status %>
  </p> 

  <p>
    <strong>Timer:</strong>
    <% if @task.timer.nil?  %>
        <strong>NA</strong>
    <% else  %> 
      <%= link_to @task.timer.time_in_minute, timer_path(@task.timer) %>
    <% end %>
  </p>

  <div><center>
    <% if current_user.type == "Administrator"  %> 
      <div class="blurred-background task-card"><%= link_to "Edit this task", edit_task_path(@task) %> </div>
      <div class="blurred-background task-card"><%= link_to "Back to tasks", tasks_path %></div>
      <div class="blurred-background task-card"><%= link_to "Destroy this task", @task, method: :delete %>  </div> 
    <% else %>
      <div class="blurred-background task-card"><%= link_to "Back to tasks", tasks_path %>  </div>
    <% end %>  
  </center></div>
</div>