config/routes.rb
Rails.application.routes.draw do
  
  root "tasks#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :timers
  get "start_timer/:id", to: "timers#start_timer", as: 'start_timer'

  resources :tasks do 
    get '/page/:page', action: :index, on: :collection
  end
  
  resource :users
  get "signin", to: "users#signin"
  post "login", to: "users#login"
  
  
end

app/models/timer.rb
class Timer < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates :time_in_minute, presence: true
end

app/controllers/timers_controller.rb
class TimersController < ApplicationController
  before_action :check_administrator, except: [:show, :start_timer]
  before_action :check_workie, only: :start_timer
  before_action :set_params, except: [:index, :create]

  def show
  end

  def start_timer
    render 'start_timer'
    task = Task.find(@timer.task_id)
    if task.assign_to == current_user.id
      if task.status != "Complete"
        t = @timer.time_in_minute * 60
        t.times do |i|
          puts "Timer is running....#{i} second"
          sleep(1)
        end

        task = task.update(status: "Complete")
        if task
          TimerMailer.with(timer: @timer).timer_complete.deliver_now
        else
          redirect_to tasks_path, notice: "Task time is completed, but there was an issue."
        end
      end
    else
      redirect_to @timer, notice: "#{User.find(task.assign_to).name} can only start the timer!!"
    end
  end

private
  def set_params
      @timer = Timer.find(params[:id])
  end

end

app/helpers/timers_helper.rb
module TimersHelper
end

app/views/timers/show.html.erb
 <center>
  <u><h3> Timer with task: <%= @timer.task.title %></h3></u>
 </center> <br>

<div class="blurred-background task-card">
  <p>
    <strong>Timer (Minutes):</strong>
    <%= @timer.time_in_minute %>
  </p>

  <p>
    <strong>Task:</strong>
    <%= @timer.task.title %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @timer.task.status %>
  </p>

  <p>
    <strong>Assigned By:</strong>
    <%= User.find(@timer.user_id).name %>
  </p>
    
  <div><center>
    <% if current_user.type == "Administrator"  %>
        <div class="blurred-background task-card"><%= link_to "Edit this timer", edit_timer_path(@timer) %></div> 
        <div class="blurred-background task-card"><%= link_to "Back to task", task_url %></div>
        <div class="blurred-background task-card"><%= link_to "Destroy this timer", @timer, method: :delete %></div>
    <% else %>
      <% if current_user.type == "Workie"  %>
        <div class="blurred-background task-card"><%= link_to "Start Timer", start_timer_path %></div>  
        <div class="blurred-background task-card"><%= link_to "Back to tasks", task_url %></div>
      <% end %>
    <% end %>  
  </center></div>
</div>

app/views/timers/start_timer.html.erb
<% if @timer.task.status == "Pending"  %>
  <%= start_timer_function() %>
  <div style="text-align: center;" class="blurred-background task-card">
    <h1>For Task: <%= @timer.task.title %>, Timer is running...</h1>
    <p id="timer">Timer: <span id="countdown"></span></p>
  </div>

  <script>
    // JavaScript to handle the countdown timer
    var timeLeft = <%= @timer.time_in_minute * 60 %>; // Convert minutes to seconds
    var countdownElement = document.getElementById('countdown');
    
    function updateTimer() {
      var minutes = Math.floor(timeLeft / 60);
      var seconds = timeLeft % 60;
      
      countdownElement.textContent = minutes + 'm ' + seconds + 's';
      
      if (timeLeft === 0) {
        clearInterval(timerInterval);
        countdownElement.textContent = 'Timer Completed';
      }
      
      timeLeft--;
    }
    
    var timerInterval = setInterval(updateTimer, 1000);
  </script>
<% else %>
  <div class="blurred-background task-card">
    <h1>For Task: <%= @timer.task.title %>, Timer is completed!!</h1>
  </div>
<% end %>